# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
# permalink: /:title.html
paginate: 5
plugins_dir: [jekyll-paginate]
port: 3000
safe: true
plugins: [jekyll-paginate]

# edit here to achieve your personal greatness
url: https://nightwhistler.net
# baseurl: /
title: Alex Kuiper
author: Alex Kuiper
description: Alex' Ramblings
avatar: profile.png
email: alex@nightwhistler.net
github: nightwhistler
twitter: nightwhistler
linkedin: alkuiper
# stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
# disqus: username
# google_analytics: UA-69391421-1

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - [vendor]
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - Rakefile
  - banner.js
  - package-lock.json
  - README.md 
  - sitemap.xml
  - CHANGELOG.md
  - jekyll-theme-so-simple.gemspec

# needed for travis-ci build
# exclude: [vendor]
